In [42]:
import pandas as pd
import numpy as np

In [5]:
pd.__version__

'2.3.1'

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
df.shape

(9704, 11)

In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [7]:
df['fuel_type'].nunique()

2

In [9]:
print(df.isnull().any().sum())

4


In [15]:
print(round(df[df['origin']=='Asia']['fuel_efficiency_mpg'].max(), 2))

23.76


In [18]:
print(df['horsepower'].median())

149.0


In [22]:
print(df['horsepower'].mode()[0])

152.0


In [20]:
df['horsepower'].isna().sum()

np.int64(708)

In [23]:
df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)

/tmp/ipykernel_12734/1392585663.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)


In [24]:
df['horsepower'].isna().sum()

np.int64(0)

In [25]:
print(df['horsepower'].median())

152.0


In [36]:
X = df.loc[df['origin']=='Asia', ['vehicle_weight', 'model_year']].head(7).to_numpy()

In [37]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [39]:
XTX = X.T @ X

In [40]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [43]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [44]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [48]:
w = inv_XTX @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [50]:
print(round(w[0] + w[1], 2))

0.52
